version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Packer..."
      - aws s3 cp s3://${PKR_VAR_s3_bucket}/packer/packer_${PACKER_VERSION}_linux_amd64.zip packer.zip || curl -qL -o packer.zip https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
      - unzip packer.zip
      - echo "Validating Packer files..."
      - ./packer validate .
  build:
    commands:
      - echo "Building AMI from Packer template..."
      - ./packer build .
  post_build:
    commands:
      - echo "Packer finished on $(date)"